apiVersion: v1
kind: Service
metadata:
  name: combined-service
spec:
  selector:
    app: combined
  ports:
    - name: combined-port
      protocol: TCP
      port: 80
      targetPort: 80 # You can use any port that your combined application listens on
  type: LoadBalancer


# apiVersion: v1
# kind: Service
# metadata:
#   name: combined-service
# spec:
#   selector:
#     app: combined
#   ports:
#     - name: frontend-port
#       protocol: TCP
#       port: 80
#       targetPort: 5173
#     - name: backend-port
#       protocol: TCP
#       port: 8000
#       targetPort: 8000
#   type: LoadBalancer
